spring:
  profiles:
    active:
      - EN
      - dog
      - prod

de:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod


de:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl:  YmlProdUrl